services:
  excelify:
    image: ghcr.io/jagac/go-excelify/go-excelify:latest
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./logs:${LOG_DIR}
    env_file:
      - .env
    restart: always
