services:
  excelify:
    build:
      context: .
      dockerfile: .dockerbuild/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./logs:/root/logs
    env_file:
      - .env
    restart: always
