global:
  scrape_interval: 5s # How often to scrape targets by default.

scrape_configs:
  - job_name: "excelify"
    static_configs:
      - targets: ["localhost:3001"] # Server's address on the same machine
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Prometheus metrics for Grafana